name: Java CI with Maven and SonarCloud

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify --file pom.xml --no-transfer-progress

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar --file pom.xml --batch-mode --no-transfer-progress \
          -Dsonar.organization=${{ vars.SONARCLOUD_ORG }} \
          -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }} \
          -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}" \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.java.libraries=target/classes

